import type {
  Profile,
  Transaction,
  Bill,
  Goal,
  AdviceHistory,
  VoiceSmsHistory,
  SafetyLog,
  Alert,
  MonthlyReport,
  Receipt,
  BudgetPlan,
  SpendingForecast,
  FamilyMember,
  Investment,
} from '@/types/types';

const iso = (value: string) => new Date(value).toISOString();

export const DEMO_USER_ID = 'user-demo-001';
export const DEMO_USER_EMAIL = 'demo@miaoda.com';

export type DemoSeedData = {
  profiles: Profile[];
  transactions: Transaction[];
  bills: Bill[];
  goals: Goal[];
  advice_history: AdviceHistory[];
  voice_sms_history: VoiceSmsHistory[];
  safety_logs: SafetyLog[];
  alerts: Alert[];
  monthly_reports: MonthlyReport[];
  receipts: Receipt[];
  budget_plans: BudgetPlan[];
  spending_forecasts: SpendingForecast[];
  family_members: FamilyMember[];
  investments: Investment[];
};

export const demoData: DemoSeedData = {
  profiles: [
    {
      id: DEMO_USER_ID,
      email: DEMO_USER_EMAIL,
      phone: '+1-415-555-0102',
      name: 'Jordan Rivers',
      language_preference: 'en',
      primary_income_type: 'Salary',
      role: 'user',
      created_at: iso('2023-11-10T08:30:00Z'),
      updated_at: iso('2024-10-01T14:15:00Z'),
    },
  ],
  family_members: [
    {
      id: 'member-self',
      user_id: DEMO_USER_ID,
      name: 'Jordan Rivers',
      relationship: 'self',
      email: DEMO_USER_EMAIL,
      phone: '+1-415-555-0102',
      date_of_birth: '1989-03-17',
      occupation: 'Product Lead',
      monthly_income: 9800,
      is_active: true,
      avatar_url: null,
      created_at: iso('2023-11-10T08:35:00Z'),
    },
    {
      id: 'member-spouse',
      user_id: DEMO_USER_ID,
      name: 'Amelia Rivers',
      relationship: 'spouse',
      email: 'amelia@rivers.family',
      phone: '+1-415-555-0194',
      date_of_birth: '1990-07-22',
      occupation: 'Freelance Designer',
      monthly_income: 4200,
      is_active: true,
      avatar_url: null,
      created_at: iso('2023-11-10T08:36:00Z'),
    },
    {
      id: 'member-teen',
      user_id: DEMO_USER_ID,
      name: 'Logan Rivers',
      relationship: 'child',
      email: null,
      phone: null,
      date_of_birth: '2011-05-06',
      occupation: null,
      monthly_income: 0,
      is_active: false,
      avatar_url: null,
      created_at: iso('2023-11-10T08:37:00Z'),
    },
  ],
  investments: [
    {
      id: 'inv-401k',
      user_id: DEMO_USER_ID,
      member_id: 'member-self',
      name: 'Growth 401k',
      type: 'stocks',
      initial_amount: 45000,
      current_value: 62500,
      purchase_date: '2018-04-01',
      expected_return_rate: 0.08,
      notes: 'Aggressive allocation with global index exposure.',
      created_at: iso('2018-04-01T15:00:00Z'),
      updated_at: iso('2024-09-15T12:00:00Z'),
    },
    {
      id: 'inv-529',
      user_id: DEMO_USER_ID,
      member_id: 'member-teen',
      name: "Logan's 529 Plan",
      type: 'mutual_funds',
      initial_amount: 12000,
      current_value: 18500,
      purchase_date: '2020-01-15',
      expected_return_rate: 0.07,
      notes: 'Age-based glide path for college savings.',
      created_at: iso('2020-01-15T17:20:00Z'),
      updated_at: iso('2024-08-28T09:45:00Z'),
    },
    {
      id: 'inv-rental',
      user_id: DEMO_USER_ID,
      member_id: null,
      name: 'SoMa Rental Loft',
      type: 'real_estate',
      initial_amount: 180000,
      current_value: 265000,
      purchase_date: '2016-09-01',
      expected_return_rate: 0.05,
      notes: 'Short-term rental with seasonal demand.',
      created_at: iso('2016-09-01T11:00:00Z'),
      updated_at: iso('2024-07-11T08:10:00Z'),
    },
  ],
  transactions: [
    {
      id: 'txn-salary-oct',
      user_id: DEMO_USER_ID,
      member_id: 'member-self',
      type: 'income',
      amount: 9800,
      category: 'Salary',
      description: 'October product lead salary',
      date: '2024-10-01',
      created_at: iso('2024-10-01T08:00:00Z'),
    },
    {
      id: 'txn-spouse-retainer',
      user_id: DEMO_USER_ID,
      member_id: 'member-spouse',
      type: 'income',
      amount: 2800,
      category: 'Freelance',
      description: 'Design retainer - wellness brand',
      date: '2024-10-05',
      created_at: iso('2024-10-05T10:15:00Z'),
    },
    {
      id: 'txn-bonus-q3',
      user_id: DEMO_USER_ID,
      member_id: 'member-self',
      type: 'income',
      amount: 3500,
      category: 'Bonus',
      description: 'Q3 performance bonus',
      date: '2024-09-20',
      created_at: iso('2024-09-20T13:00:00Z'),
    },
    {
      id: 'txn-rent-oct',
      user_id: DEMO_USER_ID,
      member_id: null,
      type: 'expense',
      amount: 3800,
      category: 'Housing',
      description: 'Mission District rent',
      date: '2024-10-02',
      created_at: iso('2024-10-02T07:20:00Z'),
    },
    {
      id: 'txn-groceries',
      user_id: DEMO_USER_ID,
      member_id: null,
      type: 'expense',
      amount: 325.4,
      category: 'Groceries',
      description: 'Harvest Market weekly run',
      date: '2024-10-04',
      created_at: iso('2024-10-04T19:30:00Z'),
    },
    {
      id: 'txn-kid-activities',
      user_id: DEMO_USER_ID,
      member_id: 'member-teen',
      type: 'expense',
      amount: 210,
      category: 'Education',
      description: 'Robotics club dues',
      date: '2024-09-29',
      created_at: iso('2024-09-29T16:45:00Z'),
    },
    {
      id: 'txn-dining',
      user_id: DEMO_USER_ID,
      member_id: null,
      type: 'expense',
      amount: 142.75,
      category: 'Dining',
      description: 'Anniversary dinner at Lumen',
      date: '2024-09-27',
      created_at: iso('2024-09-27T23:10:00Z'),
    },
    {
      id: 'txn-utilities',
      user_id: DEMO_USER_ID,
      member_id: null,
      type: 'expense',
      amount: 186.2,
      category: 'Utilities',
      description: 'PG&E + water',
      date: '2024-09-25',
      created_at: iso('2024-09-25T09:00:00Z'),
    },
  ],
  bills: [
    {
      id: 'bill-rent',
      user_id: DEMO_USER_ID,
      name: 'Mission District Loft',
      amount: 3800,
      due_date: '2024-11-01',
      status: 'upcoming',
      category: 'Housing',
      created_at: iso('2024-10-01T07:30:00Z'),
    },
    {
      id: 'bill-internet',
      user_id: DEMO_USER_ID,
      name: 'Fiber Internet',
      amount: 125.99,
      due_date: '2024-10-18',
      status: 'upcoming',
      category: 'Utilities',
      created_at: iso('2024-09-18T12:15:00Z'),
    },
    {
      id: 'bill-car',
      user_id: DEMO_USER_ID,
      name: 'EV Lease',
      amount: 610.45,
      due_date: '2024-10-22',
      status: 'upcoming',
      category: 'Transportation',
      created_at: iso('2024-09-22T08:05:00Z'),
    },
    {
      id: 'bill-gym',
      user_id: DEMO_USER_ID,
      name: 'Family Fitness Membership',
      amount: 129.99,
      due_date: '2024-10-12',
      status: 'paid',
      category: 'Health',
      created_at: iso('2024-09-12T10:40:00Z'),
    },
  ],
  goals: [
    {
      id: 'goal-emergency',
      user_id: DEMO_USER_ID,
      name: '6-Month Emergency Fund',
      target_amount: 60000,
      current_amount: 42800,
      deadline: '2025-06-01',
      created_at: iso('2024-01-04T15:20:00Z'),
    },
    {
      id: 'goal-vacation',
      user_id: DEMO_USER_ID,
      name: 'Summer Alps Trek',
      target_amount: 9500,
      current_amount: 3200,
      deadline: '2025-08-10',
      created_at: iso('2024-06-12T09:10:00Z'),
    },
    {
      id: 'goal-college',
      user_id: DEMO_USER_ID,
      name: 'Logan Freshman Year',
      target_amount: 28000,
      current_amount: 18500,
      deadline: '2029-09-01',
      created_at: iso('2023-09-10T11:45:00Z'),
    },
  ],
  advice_history: [
    {
      id: 'advice-cash',
      user_id: DEMO_USER_ID,
      category: 'savings',
      question: 'How can I speed up my emergency fund progress?',
      answer: 'Divert half of every bonus to the emergency fund and cap discretionary spend at $1,200 for the next 3 months.',
      created_at: iso('2024-09-15T18:42:00Z'),
    },
    {
      id: 'advice-rainy-day',
      user_id: DEMO_USER_ID,
      category: 'emergency',
      question: 'Is my cash buffer enough if freelance income slows?',
      answer: 'With 4.5 months saved, build to 6 months before adding new recurring expenses.',
      created_at: iso('2024-08-08T14:10:00Z'),
    },
    {
      id: 'advice-goal',
      user_id: DEMO_USER_ID,
      category: 'planning',
      question: 'How much should I allocate monthly to the Alps trip?',
      answer: 'Set aside $550 monthly to stay on pace and use travel card bonuses for flights.',
      created_at: iso('2024-07-02T09:00:00Z'),
    },
  ],
  voice_sms_history: [
    {
      id: 'voice-checkin',
      user_id: DEMO_USER_ID,
      type: 'voice',
      content: 'Weekly spending check-in call',
      summary: 'Confirmed groceries spike and agreed on new grocery cap.',
      created_at: iso('2024-09-30T17:05:00Z'),
    },
    {
      id: 'sms-alert',
      user_id: DEMO_USER_ID,
      type: 'sms',
      content: 'Text alert: PG&E bill ready',
      summary: 'User acknowledged and scheduled payment.',
      created_at: iso('2024-09-18T12:45:00Z'),
    },
  ],
  safety_logs: [
    {
      id: 'safety-asr',
      user_id: DEMO_USER_ID,
      log_type: 'asr_failure',
      description: 'Voice model mis-heard spending category.',
      risk_score: 12,
      created_at: iso('2024-08-19T15:20:00Z'),
    },
    {
      id: 'safety-high-risk',
      user_id: DEMO_USER_ID,
      log_type: 'high_risk',
      description: 'Detected duplicate ACH attempt flagged by bank.',
      risk_score: 68,
      created_at: iso('2024-07-22T04:10:00Z'),
    },
  ],
  alerts: [
    {
      id: 'alert-rent',
      user_id: DEMO_USER_ID,
      type: 'bill_due',
      title: 'Rent due in 3 days',
      message: 'Your Mission District rent is due Friday. Schedule payment to avoid a late fee.',
      severity: 'warning',
      is_read: false,
      created_at: iso('2024-10-09T12:00:00Z'),
    },
    {
      id: 'alert-groceries',
      user_id: DEMO_USER_ID,
      type: 'overspend_warning',
      title: 'Groceries running hot',
      message: 'You have spent 82% of the grocery plan by week 2.',
      severity: 'info',
      is_read: true,
      created_at: iso('2024-09-16T09:30:00Z'),
    },
    {
      id: 'alert-goal',
      user_id: DEMO_USER_ID,
      type: 'goal_behind',
      title: 'Emergency fund behind pace',
      message: 'Add $900 this month to stay on track for a 6-month cushion.',
      severity: 'warning',
      is_read: false,
      created_at: iso('2024-09-05T11:50:00Z'),
    },
  ],
  monthly_reports: [
    {
      id: 'mr-2024-09',
      user_id: DEMO_USER_ID,
      month: '2024-09',
      total_income: 13700,
      total_expenses: 8650,
      biggest_category: 'Housing',
      biggest_category_amount: 3800,
      good_habits: ['Increased 401k deferral', 'Automated bill payments'],
      bad_habits: ['Dining out 22% above target'],
      suggestions: ['Cap dining at $400', 'Shift bonus to emergency fund'],
      created_at: iso('2024-10-01T10:00:00Z'),
    },
    {
      id: 'mr-2024-08',
      user_id: DEMO_USER_ID,
      month: '2024-08',
      total_income: 12100,
      total_expenses: 8120,
      biggest_category: 'Travel',
      biggest_category_amount: 1600,
      good_habits: ['Kept utilities under target'],
      bad_habits: ['Travel impulse purchase'],
      suggestions: ['Use sinking fund for travel'],
      created_at: iso('2024-09-01T10:00:00Z'),
    },
    {
      id: 'mr-2024-07',
      user_id: DEMO_USER_ID,
      month: '2024-07',
      total_income: 12050,
      total_expenses: 7980,
      biggest_category: 'Education',
      biggest_category_amount: 1200,
      good_habits: ['Paid summer camp early for discount'],
      bad_habits: null,
      suggestions: ['Increase auto-transfer to college fund'],
      created_at: iso('2024-08-01T10:00:00Z'),
    },
  ],
  receipts: [
    {
      id: 'receipt-market',
      user_id: DEMO_USER_ID,
      image_url: '/receipts/harvest-market.png',
      amount: 112.47,
      merchant: 'Harvest Market',
      date: '2024-10-04',
      category: 'Groceries',
      tax_amount: 8.63,
      extracted_data: {
        vendor: 'Harvest Market',
        items: [
          { name: 'Organic produce', amount: 42.83 },
          { name: 'Pantry staples', amount: 34.21 },
          { name: 'Household goods', amount: 35.43 },
        ],
      },
      created_at: iso('2024-10-04T19:45:00Z'),
    },
    {
      id: 'receipt-boutique',
      user_id: DEMO_USER_ID,
      image_url: '/receipts/aurora-boutique.png',
      amount: 268.35,
      merchant: 'Aurora Boutique',
      date: '2024-09-21',
      category: 'Shopping',
      tax_amount: 21.48,
      extracted_data: {
        vendor: 'Aurora Boutique',
        items: [
          { name: 'Outerwear', amount: 149.99 },
          { name: 'Accessories', amount: 118.36 },
        ],
      },
      created_at: iso('2024-09-21T22:05:00Z'),
    },
  ],
  budget_plans: [
    {
      id: 'budget-2024',
      user_id: DEMO_USER_ID,
      age: 35,
      income: 142000,
      responsibilities: 'Mortgage-sized rent, dependent child, rental property upkeep',
      fixed_expenses: 6200,
      lifestyle: 'Experience focused but disciplined',
      budget_percentages: {
        housing: 0.28,
        savings: 0.22,
        investing: 0.15,
        needs: 0.2,
        fun: 0.15,
      },
      savings_plan: 'Automate transfers on payday and sweep leftover cash each Friday.',
      emergency_fund_target: 60000,
      investment_split: {
        retirement: 0.55,
        brokerage: 0.25,
        real_estate: 0.2,
      },
      created_at: iso('2024-05-10T11:40:00Z'),
    },
  ],
  spending_forecasts: [
    {
      id: 'forecast-oct',
      user_id: DEMO_USER_ID,
      forecast_month: '2024-10',
      predicted_expenses: 9240,
      predicted_income: 13200,
      cash_shortage_date: null,
      overspend_risk: 'medium',
      safe_to_spend: 1480,
      confidence_score: 0.76,
      created_at: iso('2024-09-30T09:20:00Z'),
    },
    {
      id: 'forecast-nov',
      user_id: DEMO_USER_ID,
      forecast_month: '2024-11',
      predicted_expenses: 9780,
      predicted_income: 13400,
      cash_shortage_date: '2024-11-24',
      overspend_risk: 'high',
      safe_to_spend: 820,
      confidence_score: 0.68,
      created_at: iso('2024-10-08T13:55:00Z'),
    },
  ],
};
